package requests

const (
	SORT_COLUMN_DATE = "created_at"
	SORT_COLUMN_NAME = "name"

	SORT_ORDER_DESC = "desc"
	SORT_ORDER_ASC  = "asc"

	FETCH_TYPE_REQUEST      = "REQUEST"
	FETCH_TYPE_PAYMENT      = "PAYMENT"
	FETCH_TYPE_REFUND       = "REFUND"
	FETCH_TYPE_SUBSCRIPTION = "SUBSCRIPTION"
	FETCH_TYPE_NOTIFICATION = "NOTIFICATION"

	NOTIFICATION_TYPE_PAYMENT = "payment:created"
	NOTIFICATION_TYPE_REFUND  = "refund:created"
)
